// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDptwjsq7oP41yM9M484-XqAmnh8znegKA',
    appId: '1:122881809102:web:b6cb27cab7e5e381790e9f',
    messagingSenderId: '122881809102',
    projectId: 'flutter-cases',
    authDomain: 'flutter-cases.firebaseapp.com',
    storageBucket: 'flutter-cases.appspot.com',
    measurementId: 'G-T0GB5QZ900',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bSGE7FwVP60MMwsBXEC3IOhBywh7DGg',
    appId: '1:122881809102:android:523cd91940047e04790e9f',
    messagingSenderId: '122881809102',
    projectId: 'flutter-cases',
    storageBucket: 'flutter-cases.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRs4muOj_SHbqim9fLO63xPh0F-Iw4Gs',
    appId: '1:122881809102:ios:3b97bd383334a1e0790e9f',
    messagingSenderId: '122881809102',
    projectId: 'flutter-cases',
    storageBucket: 'flutter-cases.appspot.com',
    iosClientId:
        '122881809102-k4p2buuipjfnnnn3nrhmraidijv5s0at.apps.googleusercontent.com',
    iosBundleId: 'wang.dreamer2q.flutter-cases',
  );
}
